
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8080


logging:
  # Mức độ log toàn bộ ứng dụng
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: ERROR
    ch.qos.logback: OFF

  # Ghi log vào file
  file:
    name: logs/application.log

  # Cấu hình log vào console
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
