

spring:
  jackson:
    serialization:
      indent_output: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  output:
    ansi:
      enabled: ALWAYS
  data:
    redis:
      sentinel:
        master: 11
        nodes: 11
      password: 11
      client-type: lettuce
      lettuce:
        pool:
          max-active: 8
          max-idle: 50
          min-idle: 1
          max-wait: 10000
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      keepalive-time: 30000
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8080
  servlet:
    context-path: /evolve

app:
  redis:
    teller-prefix: TELLER
  config:
    api-prefix: /api

logging:
  # Mức độ log toàn bộ ứng dụng
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: ERROR
    ch.qos.logback: OFF

  # Ghi log vào file
  file:
    name: logs/application.log

  # Cấu hình log vào console
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
